'use strict';
const app = require('express')();
const morgan = require('morgan');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const helmet = require('helmet');
require('dotenv').config({silent: true});
app.use(cookieParser());
app.use(bodyParser.json({ limit: '50mb' }));
app.use(bodyParser.urlencoded({ limit: '200mb', extended: true }));
app.use(morgan('dev'));
app.use(helmet());
require('./routes')(app);
module.exports = app;