'use strict';
const app = require('express')();
const morgan = require('morgan');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const helmet = require('helmet');
require('dotenv').config({silent: true});
const config = require('./../config');
const passport = require('passport');
app.use(cookieParser());
app.use(bodyParser.json({ limit: '50mb' }));
app.use(bodyParser.urlencoded({ extended: false }));
app.use(morgan('dev'));
app.use(helmet());
require('./../config/bootstrap');
require('./../config/db')(app, config);
require('./../config/middleware/passport')(passport);
app.use(passport.initialize());
app.use(passport.session());
require('./routes')(app);
module.exports = app;